const MOOD_MESSAGES: Record<string, { present: string[]; past: string[] }> = {
  Happy: {
    present: [
      "You’re radiating happiness right now",
      "Feeling good vibes at the moment",
      "Joyful tunes are taking over your mood today",
      "Your smile is almost audible through your playlist",
      "Songs are keeping your spirits sky-high",
      "You’re in full-on happy mode today",
      "Your vibe is pure sunshine right now",
      "Cheerful beats are fueling your day",
      "You’re spreading joy without even trying",
      "Happiness is your soundtrack today",
    ],
    past: [
      "You were glowing with happiness in that period",
      "That time was filled with cheerful vibes",
      "Looks like joy defined your mood back then",
      "Happiness left its mark on that phase",
      "You were surrounded by positivity during that time",
      "That period was all about smiles and good energy",
      "The vibe back then was super uplifting",
      "Your playlist screamed joy in that phase",
      "Happiness carried you through those days",
      "That chapter was bright and cheerful",
    ],
  },
  Sad: {
    present: [
      "You seem a little down today",
      "Gentle sad songs are shaping your vibe",
      "Taking it slow and feeling mellow right now",
      "Your playlist has a soft, rainy-day feel",
      "You’re leaning into tender, emotional tracks",
      "Today feels a bit heavier, but still heartfelt",
      "Soft sadness is coloring your vibe right now",
      "You’re moving at a slower, gentler pace",
      "Your mood feels quiet and thoughtful",
      "Sadder tunes are keeping you company today",
    ],
    past: [
      "You leaned towards the sadder side during this time",
      "It was a mellow mood in that period",
      "Your vibe felt quiet and reflective back then",
      "That phase carried a soft sadness",
      "Back then, your songs mirrored rainy-day moods",
      "That period had a gentle, somber touch",
      "You were resonating with heartfelt, sad tracks",
      "Your vibe leaned heavy but introspective",
      "It was an emotionally low, softer phase",
      "Sad but soulful defined that period",
    ],
  },
  Romantic: {
    present: [
      "Love is in the air",
      "Romantic vibes are your soundtrack today",
      "Your heart’s definitely in the feels right now",
      "You’re glowing with love-filled energy",
      "Today’s playlist feels like a love letter",
      "You’re vibing with sweet, romantic tunes",
      "Your heart is steering your song choices",
      "Love songs are painting your vibe today",
      "Everything feels dreamy and tender right now",
      "Your playlist is giving pure romantic feels",
    ],
    past: [
      "Romantic energy was all around you during that time",
      "That period felt full of love songs",
      "Seems like you were in a romantic zone back then",
      "Your playlist was glowing with love",
      "Back then, vibes were soft and dreamy",
      "Romance shaped that chapter of your mood",
      "Your heart was guiding your tunes in that time",
      "Love-filled songs defined that stretch",
      "That phase was wrapped in affection",
      "The vibe was tender and deeply romantic",
    ],
  },
  Energetic: {
    present: [
      "You’re powered up and unstoppable",
      "Your playlist is pure energy today",
      "Feeling pumped and full of drive right now",
      "Adrenaline is fueling your vibe today",
      "High-energy beats are charging you up",
      "You’re unstoppable with this playlist",
      "Pure fire in your mood right now",
      "Everything feels faster, stronger, sharper",
      "Your songs are a power boost",
      "Energy is literally your soundtrack today",
    ],
    past: [
      "That time was full of unstoppable energy",
      "You were vibing with high-energy tracks back then",
      "Looks like you kept the momentum alive in that period",
      "Back then, you were fully charged up",
      "Your playlist carried pure adrenaline",
      "That phase was all about hustle and drive",
      "Energy was the signature of that time",
      "You moved through that period with high intensity",
      "It was an action-packed vibe",
      "Momentum was your fuel back then",
    ],
  },
  Calm: {
    present: [
      "Peaceful vibes surround you right now",
      "Chill mode: activated",
      "You’re in a calm, relaxing flow today",
      "Your playlist feels like a quiet breeze",
      "Stillness is your vibe right now",
      "Soft, serene energy defines today",
      "Your songs feel like pure relaxation",
      "Chill and ease are flowing through your mood",
      "You’re moving in harmony today",
      "Your music is keeping things slow and peaceful",
    ],
    past: [
      "That period was nice and calm",
      "Chill and peace defined your mood back then",
      "Your vibe was slow and easy-going at that time",
      "You leaned into peaceful, restful vibes",
      "That chapter was a serene one",
      "Back then, you were in total chill mode",
      "Your playlist felt like a quiet retreat",
      "It was all about harmony and ease",
      "That time carried soft, peaceful energy",
      "Stillness defined that period",
    ],
  },
  Motivational: {
    present: [
      "You’re crushing it with motivational beats",
      "Your music is fueling your ambition today",
      "Determined and focused vibes are shining through",
      "Your playlist feels like a pep talk",
      "You’re unstoppable with this drive",
      "Songs are firing up your determination",
      "Today’s vibe is full of hustle and growth",
      "Your beats scream motivation",
      "You’re in a strong, winning mood",
      "Energy and focus are your soundtrack today",
    ],
    past: [
      "That time was full of hustle and drive",
      "Motivation was fueling you back then",
      "Looks like your playlist kept you inspired",
      "Back then, ambition defined your vibe",
      "Your songs pushed you toward growth",
      "That chapter was all about the grind",
      "Determined energy carried you through",
      "Focus and drive were your companions",
      "That period had a winning, powerful feel",
      "Your vibe was charged with motivation",
    ],
  },
  Emotional: {
    present: [
      "You’re in an emotional space right now",
      "Heartfelt songs are shaping today’s vibe",
      "Your playlist shows you’re feeling deep and reflective",
      "You’re tuned into tender, soulful tracks",
      "The vibe is heartfelt and touching today",
      "You’re letting your emotions flow through songs",
      "Your playlist feels like pure soul therapy",
      "There’s depth and vulnerability in your vibe",
      "Today’s mood is heartfelt and expressive",
      "Emotions are guiding your soundtrack right now",
    ],
    past: [
      "That period carried a lot of emotions",
      "You were tuning into heartfelt, soulful tracks",
      "Your vibe was emotional and reflective back then",
      "That chapter was heavy with feelings",
      "Your playlist spoke the language of the heart",
      "Back then, your songs felt raw and deep",
      "It was a vulnerable, emotional stretch",
      "Your vibe carried soulful intensity",
      "That period was tender and heartfelt",
      "Music mirrored deep emotions in that time",
    ],
  },
  Unknown: {
    present: [
      "Your vibe is a mystery today",
      "Hard to pin down your mood",
      "Your playlist feels unpredictable",
      "Today’s vibe is unique and undefined",
      "You’re all over the place — in a good way",
      "No single mood is taking the spotlight",
      "A mix of everything makes today interesting",
      "You’re vibing to something totally unexpected",
      "Unclear but definitely not boring",
      "Your songs are keeping things mysterious",
    ],
    past: [
      "That period had a mix of vibes",
      "No clear mood stood out then",
      "Your playlist was unpredictable that time",
      "Back then, your vibe was a total blend",
      "It felt undefined but intriguing",
      "Your mood was hard to box in",
      "A little bit of everything shaped that phase",
      "That chapter was unpredictable but fun",
      "Mixed energy defined that period",
      "Unclear, but never boring",
    ],
  },
  Neutral: {
    present: [
      "You’re in a balanced state today",
      "Neither up nor down — just steady vibes",
      "Your playlist feels calm and centered",
      "You’re moving with a neutral, grounded flow",
      "Today’s energy is smooth and even-paced",
      "Your songs reflect balance and simplicity",
      "You’re vibing in a steady middle ground",
      "No extremes — just a clear, neutral vibe",
      "Your mood is calm and consistent today",
      "Feels like a peaceful, balanced soundtrack",
    ],
    past: [
      "That period carried a neutral, steady vibe",
      "You were balanced and grounded back then",
      "No strong highs or lows — just steady flow",
      "Your playlist reflected calm simplicity",
      "That chapter felt stable and even-keeled",
      "Your mood was smooth and centered in that time",
      "Neutral vibes carried you through those days",
      "The energy back then was consistent and peaceful",
      "It was a balanced stretch without extremes",
      "Your vibe was calm and steady during that time",
    ],
  },
};

const getMoodMessage = (category: string, isToday: boolean): string => {
  const moodSet = MOOD_MESSAGES[category] || MOOD_MESSAGES.Unknown;
  const pool = isToday ? moodSet.present : moodSet.past;
  return pool[Math.floor(Math.random() * pool.length)];
};

export { getMoodMessage };
